spring.application.name=spring-security-oauth2
server.port=8000
spring.security.oauth2.client.registration.github.client-id: Ov23ctoF1JEH32F74KSn
spring.security.oauth2.client.registration.github.client-secret: fceb8520780d9d8bdf99a6ce9d67510766e88a3e